apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: sctny36vy-nodejs 
  janus-idp.io/tekton: sctny36vy-nodejs
  backstage.io/kubernetes-id: sctny36vy-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: sctny36vy-nodejs
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  